=== blegay/http_component/Resources/extensionMimeLookup.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  
  targetNamespace="http://www.ac-consulting.fr/tech/namespace/extensionMimeLookup"
  xmlns="http://www.ac-consulting.fr/tech/namespace/extensionMimeLookup" 
  
  elementFormDefault="qualified">
  
  <xs:element name="extMimeLookupList">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="extMimeLookup"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="extMimeLookup">
    <xs:complexType>
      <xs:attribute name="extension" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="mime" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== blegay/http_component/Resources/extensionMimeLookup.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<extMimeLookupList
    xmlns="http://www.ac-consulting.fr/tech/namespace/extensionMimeLookup"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ac-consulting.fr/tech/namespace/extensionMimeLookup extensionMimeLookup.xsd">
    <!-- This list is used by HTTP__loadExtMimeLookup. This is a list of the most common extensions and corresponding mime type. 
         Bruno LEGAY - 28/08/2013 -->
    
    <extMimeLookup extension=".htm" mime="text/html"/>
    <extMimeLookup extension=".html" mime="text/html"/>
    <extMimeLookup extension=".xhtml" mime="text/html"/>    <!--Added by Bruno LEGAY - 03/09/2014-->
    <extMimeLookup extension=".shtml" mime="text/html"/>
    <extMimeLookup extension=".shtm" mime="text/html"/>
    <extMimeLookup extension=".css" mime="text/css"/>
    
    <extMimeLookup extension=".txt" mime="text/plain"/>
    <extMimeLookup extension=".text" mime="text/plain"/>
    <extMimeLookup extension=".csv" mime="text/csv"/>    <!--Added by Bruno LEGAY - 28/08/2013-->
    <!--<extMimeLookup extension=".xml" mime="text/xml"/> Added by Bruno LEGAY - 28/08/2013 mais retiré car on utilise plutôt "application/xml" -->

    <extMimeLookup extension=".pdf" mime="application/pdf"/>
    <extMimeLookup extension=".rtf" mime="application/rtf"/>
    <extMimeLookup extension=".ps" mime="application/postscript"/>
    <extMimeLookup extension=".eps" mime="application/postscript"/>
    <extMimeLookup extension=".hqx" mime="application/mac-binhex40"/>
    <extMimeLookup extension=".js" mime="application/javascript"/>
    <extMimeLookup extension=".json" mime="application/json"/>

    <extMimeLookup extension=".sit" mime="application/x-stuffit"/>
    <extMimeLookup extension=".bin" mime="application/x-stuffit"/>
    <extMimeLookup extension=".xml" mime="application/xml"/>
    <extMimeLookup extension=".z" mime="application/x-zip"/>
    <extMimeLookup extension=".zip" mime="application/x-zip"/>
    <extMimeLookup extension=".gz" mime="application/x-gzip"/>
    <extMimeLookup extension=".tar" mime="application/x-tar"/>
    
    <extMimeLookup extension=".gif" mime="image/gif"/>
    <extMimeLookup extension=".jpg" mime="image/jpeg"/>
    <extMimeLookup extension=".jpeg" mime="image/jpeg "/>
    <extMimeLookup extension=".jpe" mime="image/jpeg"/>
    <extMimeLookup extension=".jfif" mime="image/jpeg"/>
    <extMimeLookup extension=".pic" mime="image/pict"/>
    <extMimeLookup extension=".pict" mime="image/pict"/>
    <extMimeLookup extension=".tif" mime="image/tiff"/>
    <extMimeLookup extension=".tiff" mime="image/tiff"/>
    <extMimeLookup extension=".png" mime="image/png"/>    <!--Added by Bruno LEGAY - 28/08/2013-->
    <extMimeLookup extension=".svg" mime="image/svg+xml"/>    <!--Added by Bruno LEGAY - 28/08/2013-->
    <extMimeLookup extension=".bm" mime="image/bmp"/>    <!--Added by Bruno LEGAY - 26/09/2015-->
    <extMimeLookup extension=".bmp" mime="image/bmp"/>    <!--Added by Bruno LEGAY - 26/09/2015-->    

    <extMimeLookup extension=".mpeg" mime="video/mpeg"/>
    <extMimeLookup extension=".mpg" mime="video/mpeg"/>
    <extMimeLookup extension=".mov" mime="video/quicktime"/>
    <extMimeLookup extension=".moov" mime="video/quicktime"/>
    <extMimeLookup extension=".mp4" mime="video/mp4"/>    <!--Added by Bruno LEGAY - 28/08/2013-->

    <extMimeLookup extension=".aif" mime="audio/aiff"/>
    <extMimeLookup extension=".aiff" mime="audio/aiff"/>
    <extMimeLookup extension=".wav" mime="audio/wav"/>
    <extMimeLookup extension=".ram" mime="audio/x-pn-realaudio"/>
    <extMimeLookup extension=".mp3" mime="audio/mpeg"/>    <!--Added by Bruno LEGAY - 28/08/2013-->
    <!-- audio/mpeg : MP3 ou autres MPEG ; défini dans la RFC 3003 (attention, sur certains navigateurs tels que Chrome / Chromium - content-type est : audio/mp3). -->
    
    
    <!--
        http://www.sitepoint.com/web-foundations/mime-types-complete-list/
        
.dwg	application/acad
.arj	application/arj
.mm	application/base64
.mme	application/base64
.hqx	application/binhex
.hqx	application/binhex4
.boo	application/book
.book	application/book
.cdf	application/cdf
.ccad	application/clariscad
.dp	application/commonground
.drw	application/drafting
.tsp	application/dsptype
.dxf	application/dxf
.js	application/ecmascript
.evy	application/envoy
.xl	application/excel
.xla	application/excel
.xlb	application/excel
.xlc	application/excel
.xld	application/excel
.xlk	application/excel
.xll	application/excel
.xlm	application/excel
.xls	application/excel
.xlt	application/excel
.xlv	application/excel
.xlw	application/excel
.fif	application/fractals
.frl	application/freeloader
.spl	application/futuresplash
.tgz	application/gnutar
.vew	application/groupwise
.hlp	application/hlp
.hta	application/hta
.unv	application/i-deas
.iges	application/iges
.igs	application/iges
.inf	application/inf
.class	application/java
.class	application/java-byte-code
.js	application/javascript
.lha	application/lha
.lzx	application/lzx
.bin	application/mac-binary
.hqx	application/mac-binhex
.hqx	application/mac-binhex40
.cpt	application/mac-compactpro
.bin	application/macbinary
.mrc	application/marc
.mbd	application/mbedlet
.mcd	application/mcad
.aps	application/mime
.pot	application/mspowerpoint
.pps	application/mspowerpoint
.ppt	application/mspowerpoint
.ppz	application/mspowerpoint
.doc	application/msword
.dot	application/msword
.w6w	application/msword
.wiz	application/msword
.word	application/msword
.wri	application/mswrite
.mcp	application/netmc
.a	application/octet-stream
.arc	application/octet-stream
.arj	application/octet-stream
.bin	application/octet-stream
.com	application/octet-stream
.dump	application/octet-stream
.exe	application/octet-stream
.lha	application/octet-stream
.lhx	application/octet-stream
.lzh	application/octet-stream
.lzx	application/octet-stream
.o	application/octet-stream
.psd	application/octet-stream
.saveme	application/octet-stream
.uu	application/octet-stream
.zoo	application/octet-stream
.oda	application/oda
.pdf	application/pdf
.p12	application/pkcs-12
.crl	application/pkcs-crl
.p10	application/pkcs10
.p7c	application/pkcs7-mime
.p7m	application/pkcs7-mime
.p7s	application/pkcs7-signature
.cer	application/pkix-cert
.crt	application/pkix-cert
.crl	application/pkix-crl
.text	application/plain
.ai	application/postscript
.eps	application/postscript
.ps	application/postscript
.ppt	application/powerpoint
.part	application/pro_eng
.prt	application/pro_eng
.rng	application/ringing-tones
.rtf	application/rtf
.rtx	application/rtf
.sdp	application/sdp
.sea	application/sea
.set	application/set
.stl	application/sla
.smi	application/smil
.smil	application/smil
.sol	application/solids
.sdr	application/sounder
.step	application/step
.stp	application/step
.ssm	application/streamingmedia
.tbk	application/toolbook
.vda	application/vda
.fdf	application/vnd.fdf
.hgl	application/vnd.hp-hpgl
.hpg	application/vnd.hp-hpgl
.hpgl	application/vnd.hp-hpgl
.pcl	application/vnd.hp-pcl
.xlb	application/vnd.ms-excel
.xlc	application/vnd.ms-excel
.xll	application/vnd.ms-excel
.xlm	application/vnd.ms-excel
.xls	application/vnd.ms-excel
.xlw	application/vnd.ms-excel
.sst	application/vnd.ms-pki.certstore
.pko	application/vnd.ms-pki.pko
.cat	application/vnd.ms-pki.seccat
.stl	application/vnd.ms-pki.stl
.pot	application/vnd.ms-powerpoint
.ppa	application/vnd.ms-powerpoint
.pps	application/vnd.ms-powerpoint
.ppt	application/vnd.ms-powerpoint
.pwz	application/vnd.ms-powerpoint
.mpp	application/vnd.ms-project
.ncm	application/vnd.nokia.configuration-message
.rng	application/vnd.nokia.ringing-tone
.rm	application/vnd.rn-realmedia
.rnx	application/vnd.rn-realplayer
.wmlc	application/vnd.wap.wmlc
.wmlsc	application/vnd.wap.wmlscriptc
.web	application/vnd.xara
.vmd	application/vocaltec-media-desc
.vmf	application/vocaltec-media-file
.wp	application/wordperfect
.wp5	application/wordperfect
.wp6	application/wordperfect
.wpd	application/wordperfect
.w60	application/wordperfect6.0
.wp5	application/wordperfect6.0
.w61	application/wordperfect6.1
.wk1	application/x-123
.aim	application/x-aim
.aab	application/x-authorware-bin
.aam	application/x-authorware-map
.aas	application/x-authorware-seg
.bcpio	application/x-bcpio
.bin	application/x-binary
.hqx	application/x-binhex40
.bsh	application/x-bsh
.sh	application/x-bsh
.shar	application/x-bsh
.elc	application/x-bytecode.elisp (compiled elisp)
.pyc	application/x-bytecode.python
.bz	application/x-bzip
.boz	application/x-bzip2
.bz2	application/x-bzip2
.cdf	application/x-cdf
.vcd	application/x-cdlink
.cha	application/x-chat
.chat	application/x-chat
.ras	application/x-cmu-raster
.cco	application/x-cocoa
.cpt	application/x-compactpro
.z	application/x-compress
.gz	application/x-compressed
.tgz	application/x-compressed
.z	application/x-compressed
.zip	application/x-compressed
.nsc	application/x-conference
.cpio	application/x-cpio
.cpt	application/x-cpt
.csh	application/x-csh
.deepv	application/x-deepv
.dcr	application/x-director
.dir	application/x-director
.dxr	application/x-director
.dvi	application/x-dvi
.elc	application/x-elc
.env	application/x-envoy
.evy	application/x-envoy
.es	application/x-esrehber
.xla	application/x-excel
.xlb	application/x-excel
.xlc	application/x-excel
.xld	application/x-excel
.xlk	application/x-excel
.xll	application/x-excel
.xlm	application/x-excel
.xls	application/x-excel
.xlt	application/x-excel
.xlv	application/x-excel
.xlw	application/x-excel
.mif	application/x-frame
.pre	application/x-freelance
.gsp	application/x-gsp
.gss	application/x-gss
.gtar	application/x-gtar
.gz	application/x-gzip
.gzip	application/x-gzip
.hdf	application/x-hdf
.help	application/x-helpfile
.hlp	application/x-helpfile
.imap	application/x-httpd-imap
.ima	application/x-ima
.ins	application/x-internett-signup
.iv	application/x-inventor
.ip	application/x-ip2
.class	application/x-java-class
.jcm	application/x-java-commerce
.js	application/x-javascript
